export enum EBonusAttribute {
  CritDmg = 'crit-dmg',
  ElementalMastery = 'elemental-mastery',
  EnergyRecharge = 'energy-recharge',
  CritRate = 'crit-rate',
  Hp = 'hp',
  HealingBonus = 'healing-bonus',
  PhysicalDmgBonus = 'physical-dmg-bonus',
  Atk = 'atk',
  Def = 'def',
  PyroDmgBonus = 'pyro-dmg-bonus',
  HydroDmgBonus = 'hydro-dmg-bonus',
  DendroDmgBonus = 'dendro-dmg-bonus',
  ElectroDmgBonus = 'electro-dmg-bonus',
  CryoDmgBonus = 'cryo-dmg-bonus',
  AnemoDmgBonus = 'anemo-dmg-bonus',
  GeoDmgBonus = 'geo-dmg-bonus',
  Other = 'other',
}
