import { IFormMetadata } from "../../../shared/interfaces/form.interface";
import { EFormType } from "../../../core/enums/form.enum";
import { ELanguage } from "../../../core/enums/language.enum";

export const detailsMetadata: IFormMetadata[] = [
  {
    fieldName: 'name',
    label: 'page.materials.ascension.field.name.en',
    type: EFormType.String,
    option: '',
    language: ELanguage.English,
    valueTranslateKey: '',
    checkboxes: [],
  },
  {
    fieldName: 'name',
    label: 'page.materials.ascension.field.name.ua',
    type: EFormType.String,
    option: '',
    language: ELanguage.Ukrainian,
    valueTranslateKey: '',
    checkboxes: [],
  },
  {
    fieldName: 'name',
    label: 'page.materials.ascension.field.name.ru',
    type: EFormType.String,
    option: '',
    language: ELanguage.Russian,
    valueTranslateKey: '',
    checkboxes: [],
  },
  {
    fieldName: 'description',
    label: 'page.materials.ascension.field.description.en',
    type: EFormType.String,
    option: '',
    language: ELanguage.English,
    valueTranslateKey: '',
    checkboxes: [],
  },
  {
    fieldName: 'description',
    label: 'page.materials.ascension.field.description.ua',
    type: EFormType.String,
    option: '',
    language: ELanguage.Ukrainian,
    valueTranslateKey: '',
    checkboxes: [],
  },
  {
    fieldName: 'description',
    label: 'page.materials.ascension.field.description.ru',
    type: EFormType.String,
    option: '',
    language: ELanguage.Russian,
    valueTranslateKey: '',
    checkboxes: [],
  },
  {
    fieldName: 'type',
    label: 'page.materials.ascension.field.type',
    type: EFormType.Option,
    option: '',
    language: '',
    valueTranslateKey: 'enum.ascension-type.',
    checkboxes: [],
  },
  {
    fieldName: 'rarity',
    label: 'page.materials.ascension.field.rarity',
    type: EFormType.Option,
    option: '',
    language: '',
    valueTranslateKey: 'enum.rarity.',
    checkboxes: [],
  },
  {
    fieldName: 'icon',
    label: 'page.materials.ascension.field.icon',
    type: EFormType.Image,
    option: '',
    language: '',
    valueTranslateKey: '',
    checkboxes: [],
  },
];
