import { IFormMetadata } from '../../../shared/interfaces/form.interface';
import { EFormType } from '../../../core/enums/form.enum';

export const editMetadata: IFormMetadata[] = [
  {
    fieldName: 'nameEn',
    label: 'page.materials.ascension.field.name.en',
    type: EFormType.String,
    option: '',
    language: '',
    valueTranslateKey: '',
    checkboxes: [],
  },
  {
    fieldName: 'nameUa',
    label: 'page.materials.ascension.field.name.ua',
    type: EFormType.String,
    option: '',
    language: '',
    valueTranslateKey: '',
    checkboxes: [],
  },
  {
    fieldName: 'nameRu',
    label: 'page.materials.ascension.field.name.ru',
    type: EFormType.String,
    option: '',
    language: '',
    valueTranslateKey: '',
    checkboxes: [],
  },
  {
    fieldName: 'descriptionEn',
    label: 'page.materials.ascension.field.description.en',
    type: EFormType.String,
    option: '',
    language: '',
    valueTranslateKey: '',
    checkboxes: [],
  },
  {
    fieldName: 'descriptionUa',
    label: 'page.materials.ascension.field.description.ua',
    type: EFormType.String,
    option: '',
    language: '',
    valueTranslateKey: '',
    checkboxes: [],
  },
  {
    fieldName: 'descriptionRu',
    label: 'page.materials.ascension.field.description.ru',
    type: EFormType.String,
    option: '',
    language: '',
    valueTranslateKey: '',
    checkboxes: [],
  },
  {
    fieldName: 'type',
    label: 'page.materials.ascension.field.type',
    type: EFormType.Option,
    option: 'type',
    language: '',
    valueTranslateKey: '',
    checkboxes: [],
  },
  {
    fieldName: 'rarity',
    label: 'page.materials.ascension.field.rarity',
    type: EFormType.Option,
    option: 'rarity',
    language: '',
    valueTranslateKey: '',
    checkboxes: [],
  },
  {
    fieldName: 'icon',
    label: 'page.materials.ascension.field.icon',
    type: EFormType.Image,
    option: '',
    language: '',
    valueTranslateKey: '',
    checkboxes: [],
  },
];
