export enum EPage {
  Empty = '',
  Authorization = 'authorization',
  Main = 'main',
  Account = 'account',
  Admin = 'admin',
  User = 'user',
  Character = 'character',
  Traveler = 'traveler',
  Weapon = 'weapon',
  Material = 'materials',
  CharacterWeaponUpgrades = 'character-and-weapon-upgrades',
  CharacterDevelopment = 'character-development',
  CharacterElevation = 'character-elevation',
  CharacterTalents = 'character-talents',
  Enemy = 'enemy',
  Mob = 'mob',
  EliteBoss = 'elite-boss',
  WeeklyBoss = 'weekly-boss',
  Settings = 'settings',
}
