export enum EPage {
  Empty = '',
  Authorization = 'authorization',
  Main = 'main',
  Accounts = 'accounts',
  Admins = 'admins',
  Users = 'users',
  Characters = 'characters',
  Traveler = 'traveler',
  Weapons = 'weapons',
  Material = 'materials',
  CharactersWeaponEnhancement = 'characters-and-weapon-enhancement',
  CharacterLevelUp = 'character-level-up',
  CharacterAscension = 'character-ascension',
  CharacterTalents = 'character-talents',
  Enemies = 'enemies',
  Mobs = 'mobs',
  EliteBosses = 'elite-bosses',
  WeeklyBosses = 'weekly-bosses',
  Settings = 'settings',
  Other = 'other',
  View = 'view',
  Create = 'create',
  Edit = 'edit',
  Details = 'details',
  ParamId = '/:id',
}
