export enum EHeaderType {
  Id = 'id',
  String = 'string',
  Quality = 'quality',
  Element = 'element',
  Region = 'region',
  BonusAttribute = 'bonus-attribute',
  Weapon = 'weapon',
  Array = 'array',
  Arche = 'Arche',
  Date = 'date',
  Link = 'link',
  TranslateString = 'translate-string',
  Action = 'action',
}
