import { IFormMetadata } from "../../../shared/interfaces/form.interface";
import { EFormType } from "../../../core/enums/form.enum";

export const createMetadata: IFormMetadata[] = [
  {
    fieldName: 'nameEn',
    label: 'page.create.field.name.en',
    type: EFormType.String,
    option: '',
    language: '',
    valueTranslateKey: '',
    checkboxes: [],
  },
  {
    fieldName: 'nameUa',
    label: 'page.create.field.name.ua',
    type: EFormType.String,
    option: '',
    language: '',
    valueTranslateKey: '',
    checkboxes: [],
  },
  {
    fieldName: 'nameRu',
    label: 'page.create.field.name.ru',
    type: EFormType.String,
    option: '',
    language: '',
    valueTranslateKey: '',
    checkboxes: [],
  },
  {
    fieldName: 'descriptionEn',
    label: 'page.create.field.description.en',
    type: EFormType.String,
    option: '',
    language: '',
    valueTranslateKey: '',
    checkboxes: [],
  },
  {
    fieldName: 'descriptionUa',
    label: 'page.create.field.description.ua',
    type: EFormType.String,
    option: '',
    language: '',
    valueTranslateKey: '',
    checkboxes: [],
  },
  {
    fieldName: 'descriptionRu',
    label: 'page.create.field.description.ru',
    type: EFormType.String,
    option: '',
    language: '',
    valueTranslateKey: '',
    checkboxes: [],
  },
  {
    fieldName: 'abilityDescriptionEn',
    label: 'page.create.field.ability-description.en',
    type: EFormType.String,
    option: '',
    language: '',
    valueTranslateKey: '',
    checkboxes: [],
  },
  {
    fieldName: 'abilityDescriptionUa',
    label: 'page.create.field.ability-description.ua',
    type: EFormType.String,
    option: '',
    language: '',
    valueTranslateKey: '',
    checkboxes: [],
  },
  {
    fieldName: 'abilityDescriptionRu',
    label: 'page.create.field.ability-description.ru',
    type: EFormType.String,
    option: '',
    language: '',
    valueTranslateKey: '',
    checkboxes: [],
  },
  {
    fieldName: 'type',
    label: 'page.create.field.type',
    type: EFormType.Option,
    option: 'type',
    language: '',
    valueTranslateKey: '',
    checkboxes: [],
  },
  {
    fieldName: 'bonusAttribute',
    label: 'page.create.field.bonus-attribute',
    type: EFormType.Option,
    option: 'bonusAttribute',
    language: '',
    valueTranslateKey: '',
    checkboxes: [],
  },
  {
    fieldName: 'quality',
    label: 'page.create.field.quality',
    type: EFormType.Option,
    option: 'quality',
    language: '',
    valueTranslateKey: '',
    checkboxes: [],
  },
  {
    fieldName: 'region',
    label: 'page.create.field.region',
    type: EFormType.Option,
    option: 'region',
    language: '',
    valueTranslateKey: '',
    checkboxes: [],
  },
  {
    fieldName: 'splashArtOriginal',
    label: 'page.create.field.splash-art-original',
    type: EFormType.String,
    option: 'splashArtOriginal',
    language: '',
    valueTranslateKey: '',
    checkboxes: [],
  },
  {
    fieldName: 'splashArtAwakened',
    label: 'page.create.field.splash-art-awakened',
    type: EFormType.String,
    option: 'splashArtAwakened',
    language: '',
    valueTranslateKey: '',
    checkboxes: [],
  },
  {
    fieldName: 'splashArtPneuma',
    label: 'page.create.field.splash-art-pneuma',
    type: EFormType.String,
    option: 'splashArtPneuma',
    language: '',
    valueTranslateKey: '',
    checkboxes: [],
  },
  {
    fieldName: 'splashArtOusia',
    label: 'page.create.field.splash-art-ousia',
    type: EFormType.String,
    option: 'splashArtOusia',
    language: '',
    valueTranslateKey: '',
    checkboxes: [],
  },
];
