import { IFormMetadata } from "../../../shared/interfaces/form.interface";
import { EFormType } from "../../../core/enums/form.enum";
import { ELanguage } from "../../../core/enums/language.enum";

export const detailsMetadata: IFormMetadata[] = [
  {
    fieldName: 'name',
    label: 'page.details.field.name.en',
    type: EFormType.String,
    option: '',
    language: ELanguage.English,
    valueTranslateKey: '',
    checkboxes: [],
  },
  {
    fieldName: 'name',
    label: 'page.details.field.name.ua',
    type: EFormType.String,
    option: '',
    language: ELanguage.Ukrainian,
    valueTranslateKey: '',
    checkboxes: [],
  },
  {
    fieldName: 'name',
    label: 'page.details.field.name.ru',
    type: EFormType.String,
    option: '',
    language: ELanguage.Russian,
    valueTranslateKey: '',
    checkboxes: [],
  },
  {
    fieldName: 'description',
    label: 'page.details.field.description.en',
    type: EFormType.String,
    option: '',
    language: ELanguage.English,
    valueTranslateKey: '',
    checkboxes: [],
  },
  {
    fieldName: 'description',
    label: 'page.details.field.description.ua',
    type: EFormType.String,
    option: '',
    language: ELanguage.Ukrainian,
    valueTranslateKey: '',
    checkboxes: [],
  },
  {
    fieldName: 'description',
    label: 'page.details.field.description.ru',
    type: EFormType.String,
    option: '',
    language: ELanguage.Russian,
    valueTranslateKey: '',
    checkboxes: [],
  },
  {
    fieldName: 'abilityDescription',
    label: 'page.details.field.ability-description.en',
    type: EFormType.String,
    option: '',
    language: ELanguage.English,
    valueTranslateKey: '',
    checkboxes: [],
  },
  {
    fieldName: 'abilityDescription',
    label: 'page.details.field.ability-description.ua',
    type: EFormType.String,
    option: '',
    language: ELanguage.Ukrainian,
    valueTranslateKey: '',
    checkboxes: [],
  },
  {
    fieldName: 'abilityDescription',
    label: 'page.details.field.ability-description.ru',
    type: EFormType.String,
    option: '',
    language: ELanguage.Russian,
    valueTranslateKey: '',
    checkboxes: [],
  },
  {
    fieldName: 'type',
    label: 'page.details.field.type',
    type: EFormType.Option,
    option: '',
    language: '',
    valueTranslateKey: 'enum.weapon-type.',
    checkboxes: [],
  },
  {
    fieldName: 'bonusAttribute',
    label: 'page.details.field.bonus-attribute',
    type: EFormType.Option,
    option: '',
    language: '',
    valueTranslateKey: 'enum.weapon-bonus-attribute.',
    checkboxes: [],
  },
  {
    fieldName: 'quality',
    label: 'page.details.field.quality',
    type: EFormType.Option,
    option: '',
    language: '',
    valueTranslateKey: 'enum.quality.',
    checkboxes: [],
  },
  {
    fieldName: 'region',
    label: 'page.details.field.region',
    type: EFormType.Option,
    option: '',
    language: '',
    valueTranslateKey: 'enum.region.',
    checkboxes: [],
  },
  {
    fieldName: 'splashArtOriginal',
    label: 'page.details.field.splash-art-original',
    type: EFormType.String,
    option: '',
    language: '',
    valueTranslateKey: '',
    checkboxes: [],
  },
  {
    fieldName: 'splashArtAwakened',
    label: 'page.details.field.splash-art-awakened',
    type: EFormType.String,
    option: '',
    language: '',
    valueTranslateKey: '',
    checkboxes: [],
  },
  {
    fieldName: 'splashArtPneuma',
    label: 'page.details.field.splash-art-pneuma',
    type: EFormType.String,
    option: '',
    language: '',
    valueTranslateKey: '',
    checkboxes: [],
  },
  {
    fieldName: 'splashArtOusia',
    label: 'page.details.field.splash-art-ousia',
    type: EFormType.String,
    option: '',
    language: '',
    valueTranslateKey: '',
    checkboxes: [],
  },
];
